name: "DEV IMAGE BUILD"

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      packer_version: "1.9.4"

    steps:
      - name: "repository checkout"
        uses: actions/checkout@v3

      - name: "packer installation"
        uses: hashicorp/setup-packer@main
        with:
          version: ${{ env.packer_version }}

      - name: "Run packer init"
        run: packer init .
        working-directory: ./packer/

      - name: "Run packer validate"
        run: packer validate -var-file="dev.pkvars.hcl" .
        working-directory: ./packer/

      - name: "Run packer template"
        run: packer fmt .
        working-directory: ./packer/

      - name: "Build Artifact"
        run: packer build -var-file="dev.pkvars.hcl" .
        working-directory: ./packer/
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.DEV_ACCESS_KEY}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.DEV_SECRET_KEY}}
          AWS_ACCESS_REGION: ${{secrets.DEV_ACCESS_REGION}}           
